//! Authored daily-journey content, shipped inside the Rust core and seeded
//! into SQLite so the mobile UI never hardcodes exercise copy.
//!
//! Source of truth: `daily_journey.json` (regenerated by
//! `scripts/generate_daily_journey.py`). The JS mock engine keeps a copy
//! under `apps/mobile/src/native/seed/` so Expo Go can load the same pack
//! without compiling Rust.

use rusqlite::Connection;
use serde_json::{json, Value};

use crate::error::{CoreError, Result};

pub const JOURNEY_ID: &str = "daily-path";
pub const TOTAL_DAYS: u32 = 30;
pub const CATALOG_DAY: u32 = 0;

const RAW: &str = include_str!("daily_journey.json");

/// Upsert the catalog (day 0) and every authored day into `journal_days`.
/// Content is replaced on each open so copy updates ship with the app;
/// user answers live in `reflections` and are never touched here.
pub fn seed_daily_journey(conn: &Connection) -> Result<()> {
    let pack: Value = serde_json::from_str(RAW).map_err(CoreError::from)?;

    conn.execute(
        "INSERT INTO journals (id, total_days) VALUES (?1, ?2)
         ON CONFLICT(id) DO UPDATE SET total_days = excluded.total_days",
        rusqlite::params![JOURNEY_ID, TOTAL_DAYS],
    )?;

    let units = pack.get("units").cloned().unwrap_or(json!([]));
    let catalog_days = pack.get("catalog").cloned().unwrap_or(json!([]));
    let catalog = json!({
        "kind": "catalog",
        "version": pack.get("version").cloned().unwrap_or(json!(1)),
        "journeyId": JOURNEY_ID,
        "totalDays": TOTAL_DAYS,
        "title": pack.get("title").cloned().unwrap_or(json!("The Inward Path")),
        "subtitle": pack.get("subtitle").cloned().unwrap_or(json!("")),
        "philosophy": pack.get("philosophy").cloned().unwrap_or(json!("")),
        "units": units,
        "days": catalog_days,
    });
    upsert_day(
        conn,
        CATALOG_DAY,
        pack.get("title")
            .and_then(|v| v.as_str())
            .unwrap_or("The Inward Path"),
        pack.get("subtitle").and_then(|v| v.as_str()),
        &catalog,
    )?;

    let days = pack
        .get("days")
        .and_then(|v| v.as_array())
        .cloned()
        .unwrap_or_default();
    for day in days {
        let number = day.get("day").and_then(|v| v.as_u64()).unwrap_or(0) as u32;
        if number == 0 {
            continue;
        }
        let title = day
            .get("theme")
            .and_then(|v| v.as_str())
            .unwrap_or("Day");
        let subtitle = day
            .get("exercise")
            .and_then(|e| e.get("title"))
            .and_then(|v| v.as_str());
        upsert_day(conn, number, title, subtitle, &day)?;
    }

    Ok(())
}

fn upsert_day(
    conn: &Connection,
    day_number: u32,
    title: &str,
    subtitle: Option<&str>,
    content: &Value,
) -> Result<()> {
    let content_json = serde_json::to_string(content).map_err(CoreError::from)?;
    conn.execute(
        "INSERT INTO journal_days (journal_id, day_number, title, subtitle, content_json)
         VALUES (?1, ?2, ?3, ?4, ?5)
         ON CONFLICT (journal_id, day_number) DO UPDATE SET
           title = excluded.title,
           subtitle = excluded.subtitle,
           content_json = excluded.content_json",
        rusqlite::params![JOURNEY_ID, day_number, title, subtitle, content_json],
    )?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pack_parses_and_has_30_days() {
        let pack: Value = serde_json::from_str(RAW).unwrap();
        assert_eq!(pack["totalDays"], 30);
        assert_eq!(pack["days"].as_array().unwrap().len(), 30);
        assert_eq!(pack["days"][0]["day"], 1);
        assert_eq!(pack["days"][29]["day"], 30);
        assert!(pack["days"][0]["morning"]["steps"].as_array().unwrap().len() >= 2);
        assert!(pack["days"][0]["exercise"]["steps"].as_array().unwrap().len() >= 2);
        assert!(pack["days"][0]["evening"]["steps"].as_array().unwrap().len() >= 2);
    }
}
