// Generated by uniffi-bindgen-react-native
//
// JNI adapter for the InwardCore TurboModule. InwardCoreModule.kt calls the
// two external functions below; each receives the Hermes jsi::Runtime pointer
// (and, for install, the JS CallInvoker) and hands it to the C++ bridge in
// apps/mobile/cpp/inward-core.cpp, which registers the UniFFI-generated
// NativeInwardCore host object into Hermes.
#include <jni.h>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvokerHolder.h>
#include "inward-core.h"

namespace jsi = facebook::jsi;
namespace react = facebook::react;

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_inwardjourney_app_InwardCoreModule_nativeInstallRustCrate(
    JNIEnv *env,
    jclass type,
    jlong rtPtr,
    jobject callInvokerHolderJavaObj
) {
    // https://github.com/realm/realm-js/blob/main/packages/realm/binding/android/src/main/cpp/io_realm_react_RealmReactModule.cpp#L122-L145
    // React Native uses the fbjni library for handling JNI, which has the
    // concept of "hybrid objects": Java objects containing a pointer to a C++
    // object. The CallInvokerHolder, which has the invokeAsync method we want,
    // is one such hybrid object. Rather than reworking our code to use fbjni
    // throughout, unpack the C++ object from the Java holder manually.

    // 1. Get the Java object referred to by the mHybridData field of the holder.
    auto callInvokerHolderClass = env->GetObjectClass(callInvokerHolderJavaObj);
    auto hybridDataField = env->GetFieldID(
        callInvokerHolderClass, "mHybridData", "Lcom/facebook/jni/HybridData;");
    auto hybridDataObj = env->GetObjectField(callInvokerHolderJavaObj, hybridDataField);

    // 2. Get the destructor Java object from mHybridData.
    auto hybridDataClass = env->FindClass("com/facebook/jni/HybridData");
    auto destructorField =
        env->GetFieldID(hybridDataClass, "mDestructor", "Lcom/facebook/jni/HybridData$Destructor;");
    auto destructorObj = env->GetObjectField(hybridDataObj, destructorField);

    // 3. Get the mNativePointer field from the destructor object.
    auto destructorClass = env->FindClass("com/facebook/jni/HybridData$Destructor");
    auto nativePointerField = env->GetFieldID(destructorClass, "mNativePointer", "J");
    auto nativePointerValue = env->GetLongField(destructorObj, nativePointerField);

    // 4. Cast the mNativePointer back to its C++ type.
    auto nativePointer = reinterpret_cast<facebook::react::CallInvokerHolder*>(nativePointerValue);
    auto jsCallInvoker = nativePointer->getCallInvoker();

    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return inwardcore::installRustCrate(*runtime, jsCallInvoker);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_inwardjourney_app_InwardCoreModule_nativeCleanupRustCrate(JNIEnv *env, jclass type, jlong rtPtr) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return inwardcore::cleanupRustCrate(*runtime);
}
