rust:
  directory: ./rust/inward_core
  manifestPath: Cargo.toml
bindings:
  ts: ./app/src/native/generated
  cpp: ./app/cpp/generated
  uniffiToml: ./rust/inward_core/uniffi.toml
ios:
  directory: ./app/ios
  frameworkName: InwardCore
android:
  directory: ./app/android
  library: inward_core
turboModule:
  cpp: ./app/cpp
  ts: ./app/src/native/generated
  specName: InwardCore
  name: InwardCore
  entrypoint: ./app/src/native/generated/index.tsx