rust:
  directory: ./rust/inward_core
  manifestPath: Cargo.toml
bindings:
  ts: ./apps/mobile/src/native/generated
  cpp: ./apps/mobile/cpp/generated
  uniffiToml: ./rust/inward_core/uniffi.toml
ios:
  directory: ./app/ios
  frameworkName: InwardCore
android:
  directory: ./apps/mobile/android
  library: inward_core
turboModule:
  cpp: ./apps/mobile/cpp
  ts: ./apps/mobile/src/native/generated
  specName: InwardCore
  name: InwardCore
  entrypoint: ./apps/mobile/src/native/generated/index.tsx