// Generated by uniffi-bindgen-react-native
//
// InwardCore TurboModule. It is the Android counterpart of the iOS
// InwardCore.mm module generated by uniffi-bindgen-react-native: it exposes
// installRustCrate()/cleanupRustCrate() to JS via RN Codegen (NativeInwardCore
// spec) and offloads the actual work to the C++ bridge in libswa-mobile.so.
package com.inwardjourney.app

import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.annotations.ReactModule
import com.facebook.react.turbomodule.core.interfaces.CallInvokerHolder

@ReactModule(name = InwardCoreModule.NAME)
class InwardCoreModule(reactContext: ReactApplicationContext) :
  NativeInwardCoreSpec(reactContext) {

  override fun getName(): String {
    return NAME
  }

  // Two native methods implemented in cpp-adapter.cpp, which forwards to
  // cpp/inward-core.cpp (namespace inwardcore, mirroring iOS InwardCore.mm).

  external fun nativeInstallRustCrate(runtimePointer: Long, callInvoker: CallInvokerHolder): Boolean
  external fun nativeCleanupRustCrate(runtimePointer: Long): Boolean

  override fun installRustCrate(): Boolean {
    val context = this.reactApplicationContext
    return nativeInstallRustCrate(
      context.javaScriptContextHolder!!.get(),
      context.jsCallInvokerHolder!!
    )
  }

  override fun cleanupRustCrate(): Boolean {
    return nativeCleanupRustCrate(
      this.reactApplicationContext.javaScriptContextHolder!!.get()
    )
  }

  companion object {
    const val NAME = "InwardCore"

    init {
      System.loadLibrary("swa-mobile")
    }
  }
}
