// Generated by uniffi-bindgen-react-native
#include "inward-core.h"
#include "generated/inward_core.hpp"

namespace inwardcore {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeInwardCore::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}