// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "swa-mobile.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "InwardCore.h"

@interface SwaMobile : NSObject <NativeSwaMobileSpec>
#else
#import <React/RCTBridgeModule.h>

@interface SwaMobile : NSObject <RCTBridgeModule>
#endif

@end