// 21-Day Deep Self-Awareness Journal — full content arc
// Weeks 1-3 follow a deepening progression:
// Week 1 (Days 1-7): Noticing — the foundation of awareness
// Week 2 (Days 8-14): Understanding — patterns, triggers, core beliefs
// Week 3 (Days 15-21): Integrating — values, identity, and sustainable practice

// Helper factory for consistent structure
function makeDay(
  day: number,
  title: string,
  quote: string,
  eyebrow: string,
  headline: string,
  body: string,
  fact: string,
  exerciseTitle: string,
  exerciseSteps: { n: number; text: string }[],
  reflections: string[],
  challengeTitle: string,
  challengeBody: string,
  challengeCount: number,
  eveningPrompts: string[],
  closingLine: string,
) {
  return {
    blocks: [
      {
        type: 'cover',
        eyebrow: `21-DAY DEEP JOURNAL · DAY ${day}`,
        title,
        quote,
      },
      {
        type: 'overview-grid',
        items: [
          { icon: 'brain', label: 'Deep Dive', sub: eyebrow },
          { icon: 'wave', label: 'Exercise', sub: exerciseTitle },
          { icon: 'person', label: 'Daily Check-In', sub: 'Mood, energy & sleep' },
          { icon: 'pen', label: 'Reflection', sub: 'Write what you notice' },
          { icon: 'check', label: 'Challenge', sub: challengeTitle },
          { icon: 'moon', label: 'Evening', sub: 'Look back on today' },
        ],
      },
      {
        type: 'learning-card',
        eyebrow: eyebrow.toUpperCase(),
        headline,
        body,
        fact,
      },
      { type: 'guided-exercise', title: exerciseTitle, steps: exerciseSteps },
      { type: 'daily-checkin' },
      { type: 'reflection-prompts', prompts: reflections },
      { type: 'tiny-challenge', title: challengeTitle, body: challengeBody, targetCount: challengeCount },
      { type: 'evening-reflection', prompts: eveningPrompts },
      { type: 'pause-point', closingLine },
    ],
  };
}

// ─── WEEK 1: NOTICING ────────────────────────────────────────────────────────

export const D21_DAY1 = makeDay(1,
  'Pause & Notice', '"You can\'t change what you don\'t notice."',
  'Autopilot vs. Awareness',
  'Your Brain on Autopilot',
  'Most of daily life runs on autopilot — ingrained routines the brain executes without conscious direction. This conserves energy, but it also means we can go hours, days, even years reacting rather than choosing. Self-awareness begins in the pause between stimulus and response.',
  'Research suggests most of our daily behaviors are habitual. But awareness — even brief moments of noticing — is the beginning of choice.',
  'Box Breathing',
  [
    { n: 1, text: 'Sit comfortably. Hands relaxed in your lap.' },
    { n: 2, text: 'Breathe in slowly for 4 counts.' },
    { n: 3, text: 'Hold for 4 counts. Then out for 4.' },
    { n: 4, text: 'Repeat 4 times. Let the breath anchor you.' },
  ],
  ['A moment today I was on autopilot was...', 'When I paused and noticed, I felt...', 'One thing I want to pay more attention to is...'],
  'Catch Autopilot 3 Times', 'Notice when you\'re doing something without choosing it. Just observing counts.',
  3,
  ['The moment I felt most present today was...', 'Tomorrow, I want to notice...'],
  'Day 1 complete. You\'ve begun something real.',
);

export const D21_DAY2 = makeDay(2,
  'Your Emotional Vocabulary', '"To name a thing is to change your relationship to it."',
  'Emotion Science',
  'The Power of Precise Language',
  'Most people operate with a vocabulary of 3–5 emotional words: happy, sad, stressed, angry, fine. But researchers have found over 27 distinct categories of emotion — and the more precisely you can name what you\'re feeling, the more effectively you can respond to it. Emotional granularity (fine-grained emotion labeling) predicts better mental health outcomes.',
  'People with greater emotional vocabulary regulate their emotions more effectively and report higher life satisfaction.',
  'The Emotion Scan',
  [
    { n: 1, text: 'Pause and breathe. Ask: what am I feeling right now?' },
    { n: 2, text: 'Go beyond the first word. What\'s underneath it?' },
    { n: 3, text: 'Find the most precise label you can.' },
    { n: 4, text: 'Notice how naming it shifts your relationship to it.' },
  ],
  ['The most precise word for how I feel right now is...', 'An emotion I have trouble naming is...', 'When I find the right word, I notice...'],
  'Expand Your Vocabulary', 'Use 5 different emotion words today — more specific than happy, sad, or fine.',
  5,
  ['An emotion today I wouldn\'t have had a name for before is...', 'A feeling I want to understand better is...'],
  'Day 2 done. Your inner landscape is becoming clearer.',
);

export const D21_DAY3 = makeDay(3,
  'The Body Knows', '"The body keeps the score."',
  'Somatic Awareness',
  'Emotions Live in the Body First',
  'Before you have a conscious thought about how you feel, your body already knows. Tension in the jaw, a tight chest, a sinking stomach — these are your nervous system\'s signals. Somatic awareness (noticing physical sensation as emotional data) is one of the most direct paths to self-understanding. Your body is speaking constantly; today, you start listening.',
  'The vagus nerve connects the gut, heart, and brain. What we call "gut feelings" are literal biological signals informing our emotional state.',
  'Body Mapping',
  [
    { n: 1, text: 'Close your eyes. Breathe slowly.' },
    { n: 2, text: 'Scan from head to toe. Where do you notice sensation?' },
    { n: 3, text: 'Don\'t judge — just observe. Tight, soft, warm, heavy, open?' },
    { n: 4, text: 'Ask: if this sensation had an emotion attached, what would it be?' },
  ],
  ['A place in my body where I often hold stress is...', 'Today, my body was trying to tell me...', 'When I feel nervous/anxious, my body first...'],
  'Check In With Your Body 4 Times', 'Pause 4 times today and simply ask: what is my body feeling right now? No need to fix anything.',
  4,
  ['A body sensation today I almost didn\'t notice was...', 'What my body needed today that I gave/didn\'t give it was...'],
  'Three days in. You\'re building a real relationship with yourself.',
);

export const D21_DAY4 = makeDay(4,
  'Thought Patterns', '"We suffer more in imagination than in reality."',
  'Cognitive Patterns',
  'The Stories You Tell Yourself',
  'The mind doesn\'t observe reality neutrally — it interprets it. And those interpretations, repeated often enough, become deeply held beliefs. Cognitive science identifies common "distortions": all-or-nothing thinking, catastrophizing, personalization, filtering. None of these patterns are moral failures — they\'re patterns learned over time. What matters is learning to see them.',
  'The brain uses shortcuts (heuristics) to make sense of the world quickly. These are useful but can create predictable errors in perception.',
  'Watching Thoughts',
  [
    { n: 1, text: 'Sit quietly. Breathe naturally.' },
    { n: 2, text: 'Notice thoughts as they arise. Don\'t engage — just observe.' },
    { n: 3, text: 'When a thought captures you, gently return to watching.' },
    { n: 4, text: 'Practice for 3–5 minutes.' },
  ],
  ['A recurring thought pattern I notice is...', 'This pattern usually shows up when...', 'A more balanced way to see this situation might be...'],
  'Name One Thinking Pattern', 'When you notice your mind telling a story, label it: "that\'s catastrophizing" or "that\'s all-or-nothing thinking." One label today.',
  1,
  ['A story my mind told today that I questioned was...', 'The thought I\'d most like to examine is...'],
  'Day 4. You\'re learning to see your own mind. Keep going.',
);

export const D21_DAY5 = makeDay(5,
  'Triggers & Reactions', '"Between stimulus and response, there is a space."',
  'Trigger Awareness',
  'What Pulls Your Strings',
  'A trigger is any cue — a word, a tone of voice, a memory, a place — that activates an automatic emotional or behavioral response. Triggers aren\'t weaknesses; they\'re signals of unmet needs, past experiences, or core beliefs. The goal isn\'t to eliminate triggers — it\'s to create that space between the trigger and your response, where choice can live.',
  'The amygdala can activate a threat response within 14 milliseconds — before conscious awareness. This is why triggers feel so sudden and powerful.',
  'The STOP Practice',
  [
    { n: 1, text: 'When activated: Stop. Just stop what you\'re doing.' },
    { n: 2, text: 'Take one slow breath. Deliberately.' },
    { n: 3, text: 'Observe: what just happened in your body and mind?' },
    { n: 4, text: 'Proceed — now with choice instead of reaction.' },
  ],
  ['A trigger that activated me today was...', 'What I felt in my body when triggered was...', 'My usual response to this trigger is... and I\'d like to respond differently by...'],
  'Track Your Triggers', 'Note each time you have a strong emotional reaction. What set it off? Just awareness — no fixing.',
  3,
  ['The trigger I most want to understand is...', 'A need underneath my most common trigger might be...'],
  'Week 1, Day 5. You\'re seeing yourself more clearly each day.',
);

export const D21_DAY6 = makeDay(6,
  'Your Relational Self', '"We are the company we keep — and the stories we tell about that company."',
  'Relational Patterns',
  'How You Are With Others',
  'Our patterns of relating — how we connect, conflict, withdraw, or pursue — are largely formed in early relationships and run automatically in adulthood. Attachment research shows that these patterns (secure, anxious, avoidant, disorganized) shape everything from friendships to work relationships. Noticing your relational style is not about labeling yourself — it\'s about understanding what needs you\'re carrying.',
  'We co-regulate emotionally with others — meaning the people around us directly influence our nervous system, often without anyone being aware of it.',
  'Relational Reflection',
  [
    { n: 1, text: 'Think of a relationship that matters to you.' },
    { n: 2, text: 'Breathe. Ask: how do I feel in this person\'s presence?' },
    { n: 3, text: 'Notice what you feel when they\'re unavailable or distant.' },
    { n: 4, text: 'Ask: what need does this relationship help me meet?' },
  ],
  ['In close relationships, my default pattern tends to be... (e.g. pulling closer, withdrawing, pleasing)', 'A need I bring to most relationships without saying it aloud is...', 'A relationship that helps me feel like my best self is... because...'],
  'Notice One Relational Pattern', 'In one interaction today, notice your default. Do you tend to over-explain? Go quiet? Seek approval? Just notice.',
  1,
  ['A relationship dynamic I\'d like to understand better is...', 'The way I feel most loved/valued by others is...'],
  'Day 6. Relationships are mirrors. You\'re learning to look.',
);

export const D21_DAY7 = makeDay(7,
  'Week One Review', '"Growth is not linear. It is spiral — you return to the same places, but from higher up."',
  'Integration — Week 1',
  'Weaving the First Thread',
  'You\'ve completed the first week. Noticing, naming, and understanding — these are the foundations of self-awareness. Nothing changes overnight; but consistent attention creates new grooves in the mind. This is not about being done. It\'s about establishing the habit of looking inward.',
  'Seven consecutive days of reflective practice is associated with measurable increases in psychological flexibility — the ability to respond to life\'s challenges with awareness instead of reactivity.',
  'Week Review Meditation',
  [
    { n: 1, text: 'Sit quietly. Let your eyes close.' },
    { n: 2, text: 'Review the past week gently, as if paging through photographs.' },
    { n: 3, text: 'Notice what stands out — not what you should remember, but what naturally arises.' },
    { n: 4, text: 'Breathe slowly. Feel gratitude for the commitment you made to yourself.' },
  ],
  ['The most significant thing I noticed about myself this week was...', 'A pattern I saw repeated more than once was...', 'Something I want to explore more deeply in week two is...'],
  'Write a Week 1 Summary', 'In a few sentences, capture the most important thing you\'re learning about yourself. Not for anyone else — for you.',
  1,
  ['If I could send one message to myself from next week, it would be...', 'I want to carry this one insight into week two...'],
  'Week 1 complete. The journey deepens. Day 8 awaits.',
);

// ─── WEEK 2: UNDERSTANDING ───────────────────────────────────────────────────

export const D21_DAY8 = makeDay(8,
  'Core Beliefs', '"Your beliefs become your thoughts. Your thoughts become your words."',
  'Core Beliefs',
  'The Beliefs Running Your Life',
  'Core beliefs are deeply held, often unconscious assumptions about yourself, others, and the world — "I am not enough," "people can\'t be trusted," "the world is dangerous." They\'re formed in childhood and reinforced by experience. They feel like facts, not beliefs. But they can be questioned, examined, and slowly updated through awareness and new experience.',
  'Core beliefs often operate as self-fulfilling prophecies: we unconsciously seek evidence that confirms them and dismiss evidence that contradicts them.',
  'Belief Excavation',
  [
    { n: 1, text: 'Breathe. Ask: what do I most deeply believe about myself?' },
    { n: 2, text: 'Let the answer arise without editing it.' },
    { n: 3, text: 'Ask: where did this belief come from?' },
    { n: 4, text: 'Ask: is this belief helping me, or limiting me?' },
  ],
  ['A belief I carry about myself that I\'ve never questioned is...', 'This belief probably formed because...', 'Evidence that this belief might not be entirely true is...'],
  'Question One Belief', 'Take one "I am..." statement that runs in the background of your life. Ask: is this a fact, or a story? What\'s one piece of evidence against it?',
  1,
  ['A belief I want to challenge more consciously is...', 'What I might believe about myself if this belief weren\'t true is...'],
  'Day 8. The deep work begins. You\'re ready for it.',
);

export const D21_DAY9 = makeDay(9,
  'The Masks We Wear', '"Authenticity is the daily practice of letting go of who we think we\'re supposed to be."',
  'Persona & Authenticity',
  'The Gap Between Public and Private Self',
  'We all wear masks — social roles, professional personas, the version of ourselves we present in different contexts. This is normal and often adaptive. But when the gap between our public and private self becomes too wide, we lose touch with who we actually are. Authenticity isn\'t radical transparency — it\'s alignment. It\'s knowing which masks you\'re wearing and choosing them consciously.',
  'Research on authenticity finds that feeling inauthentic — like you\'re performing a role — is a stronger predictor of burnout than workload alone.',
  'The Authenticity Check',
  [
    { n: 1, text: 'Think of a context where you feel most free to be yourself.' },
    { n: 2, text: 'Breathe. Notice how that feels in your body.' },
    { n: 3, text: 'Now think of a context where you feel most masked.' },
    { n: 4, text: 'Notice the difference. What changes? What hides?' },
  ],
  ['The version of myself I most often hide is...', 'A context where I feel most free to be real is...', 'A mask I wear that has become exhausting is...'],
  'Notice One Mask Today', 'In one interaction, notice when you adjust who you are to fit what you think is expected. Just awareness — no judgment.',
  1,
  ['A moment today I felt genuinely myself was...', 'What\'s one small way I could be more authentic tomorrow?'],
  'Day 9. Authenticity is a practice, not an achievement.',
);

export const D21_DAY10 = makeDay(10,
  'Boundaries & Values', '"Boundaries are the distance at which I can love you and me simultaneously."',
  'Healthy Boundaries',
  'What Boundaries Are (and Aren\'t)',
  'Boundaries are not walls — they\'re the edges that define where you end and someone else begins. They\'re not about punishing others; they\'re about protecting what matters to you. Difficulty with boundaries usually comes from fear: of abandonment, disapproval, conflict, or being seen as selfish. But the alternative — having no boundaries — typically leads to resentment, exhaustion, and disconnection from your own needs.',
  'The inability to say no often comes from the belief that your worth depends on others\' approval. Boundaries are an act of self-respect.',
  'The Boundary Breath',
  [
    { n: 1, text: 'Think of a situation where you feel overextended or resentful.' },
    { n: 2, text: 'Breathe. Ask: what need of mine is not being honored here?' },
    { n: 3, text: 'Ask: what would I ask for if I believed I deserved it?' },
    { n: 4, text: 'Breathe out. You deserve what you need.' },
  ],
  ['A relationship or situation where I feel I have weak or absent boundaries is...', 'The fear that stops me from setting this boundary is...', 'A boundary I\'d like to establish is... and I can take the first step by...'],
  'Identify One Missing Boundary', 'Where do you feel you\'re giving more than feels sustainable? Just name it — you don\'t have to fix it today.',
  1,
  ['A moment today where I honored my own needs was...', 'A moment where I wish I\'d spoken up for myself was...'],
  'Day 10. Knowing your limits is not weakness. It\'s wisdom.',
);

export const D21_DAY11 = makeDay(11,
  'Needs & Communication', '"Seek first to understand, then to be understood."',
  'Nonviolent Communication',
  'The Language Beneath the Conflict',
  'Most conflict isn\'t really about the stated issue — it\'s about unmet needs hiding beneath the surface. Marshall Rosenberg\'s Nonviolent Communication (NVC) framework offers a map: Observations (what actually happened) → Feelings (your emotional response) → Needs (what you require) → Requests (what you\'re asking for). When we learn to communicate from needs rather than blame or judgment, something fundamental shifts.',
  'Studies show that when people feel their needs are understood — even if unmet — they report significantly higher satisfaction in relationships and negotiations.',
  'Needs Inventory',
  [
    { n: 1, text: 'Think of a recurring frustration or conflict in your life.' },
    { n: 2, text: 'Ask: what am I actually feeling in this situation?' },
    { n: 3, text: 'Ask: what need of mine is not being met?' },
    { n: 4, text: 'Ask: what one request could I make that might address this need?' },
  ],
  ['In a recent frustration or conflict, the unmet need underneath it was...', 'I often communicate this need by... (withdrawing, attacking, hinting, etc.) when what would work better is...', 'One relationship where clearer communication of needs would help is...'],
  'Name Your Need', 'In one interaction today, before responding, ask yourself: what do I actually need right now?',
  1,
  ['A moment today where communicating a need would have helped is...', 'A need I rarely ask for but deeply have is...'],
  'Day 11. Knowing your needs is not being needy. It\'s being human.',
);

export const D21_DAY12 = makeDay(12,
  'The Inner Child', '"What we don\'t repair, we repeat."',
  'Developmental Patterns',
  'The Emotional History You Carry',
  'Much of how we experience life as adults is filtered through emotional templates formed in childhood. This isn\'t about blaming the past — it\'s about understanding how early experiences created patterns that still run today. When you notice a reaction that seems disproportionate to the present situation, it often means an old wound has been activated. Compassion toward that younger self is one of the most powerful tools for change.',
  'The nervous system doesn\'t distinguish between real and remembered threat. A reminder of a past hurt activates the same stress response as a present one.',
  'Inner Child Breathing',
  [
    { n: 1, text: 'Close your eyes. Breathe slowly.' },
    { n: 2, text: 'Picture yourself at a younger age — wherever feels right.' },
    { n: 3, text: 'Ask: what did that younger version of me most need to hear?' },
    { n: 4, text: 'Say it to yourself now. Let it land.' },
  ],
  ['A childhood experience that still shapes how I respond today is...', 'When I feel vulnerable or scared, I tend to act like a child who...', 'Something compassionate I want to say to my younger self is...'],
  'Write to Your Younger Self', 'Write 2–3 sentences from your present self to a younger version of you. What do they need to know?',
  1,
  ['A pattern today that felt like it belonged to a younger version of me was...', 'What that younger self needed that I can give myself now is...'],
  'Day 12. Healing old wounds doesn\'t require revisiting pain. It requires compassion.',
);

export const D21_DAY13 = makeDay(13,
  'The Stories We Inherit', '"Not everything that is faced can be changed. But nothing can be changed until it is faced."',
  'Inherited Narratives',
  'Family and Cultural Stories',
  'We don\'t only inherit genetic traits — we inherit emotional patterns, beliefs about worth and success, narratives about what life means. Family systems, cultural backgrounds, generational trauma — all of these become part of the silent curriculum we absorb growing up. Awareness of inherited stories doesn\'t mean rejecting your background; it means choosing consciously which parts of that heritage you want to carry forward.',
  'Research on epigenetics and intergenerational trauma suggests that the emotional experiences of previous generations can influence nervous system patterns in descendants.',
  'Story Archaeology',
  [
    { n: 1, text: 'Breathe. Think about the family you grew up in.' },
    { n: 2, text: 'Ask: what was the unspoken belief about success, worth, or love?' },
    { n: 3, text: 'Ask: how has that belief shown up in my own life?' },
    { n: 4, text: 'Ask: which parts of this story do I want to consciously choose to keep?' },
  ],
  ['A story my family told about success, worth, or love was...', 'I absorbed the belief that I should/shouldn\'t... because in my family...', 'A narrative I want to rewrite for myself going forward is...'],
  'Identify One Inherited Story', 'Name one belief you grew up with that you\'re now questioning. Where did it come from? Is it yours?',
  1,
  ['A value or belief I\'m grateful to have inherited is...', 'A pattern I\'m consciously choosing not to pass forward is...'],
  'Day 13. Your story is yours to revise.',
);

export const D21_DAY14 = makeDay(14,
  'Week Two Review', '"In the middle of every difficulty lies opportunity." — but first, understanding.',
  'Integration — Week 2',
  'The Ground You\'ve Covered',
  'Two weeks of deep work. You\'ve examined core beliefs, relational patterns, masks, boundaries, needs, childhood experiences, and inherited stories. This is significant. Many people never go this deep. The insights you\'ve gathered aren\'t meant to define you — they\'re meant to free you. Understanding is not the destination; it\'s the doorway.',
  'Sustained reflective practice over 14 days has been shown to increase emotional regulation, reduce reactivity, and improve interpersonal relationships.',
  'Week 2 Integration',
  [
    { n: 1, text: 'Close your eyes. Breathe deeply.' },
    { n: 2, text: 'Let the past week pass through your mind like a slow river.' },
    { n: 3, text: 'Notice what feels unresolved. And what feels clearer.' },
    { n: 4, text: 'Breathe. You don\'t need to fix anything. Just notice.' },
  ],
  ['The most confronting thing I discovered about myself this week was...', 'Something I understood about myself this week that I couldn\'t see before is...', 'The insight I most want to carry into week three is...'],
  'Week 2 Letter to Self', 'Write one paragraph to yourself about what you\'ve learned. Be warm. You\'ve done hard work.',
  1,
  ['An area where I\'ve grown this week (even just a little) is...', 'Something I want to give myself more grace about going forward is...'],
  'Week 2 complete. The final week is about integration and becoming.',
);

// ─── WEEK 3: INTEGRATING ─────────────────────────────────────────────────────

export const D21_DAY15 = makeDay(15,
  'Living Your Values', '"It is not enough to have values. One must live them."',
  'Values in Action',
  'From Understanding to Living',
  'You\'ve spent two weeks building awareness and understanding. Week three is about integration — weaving what you\'ve learned into how you actually live. Values aren\'t beliefs you hold privately; they\'re standards by which you act. Living your values means that your daily choices — how you spend your time, your attention, your words — reflect what you most deeply care about.',
  'ACT research shows that values-based action is the strongest predictor of psychological flexibility and long-term well-being.',
  'Values Check-In',
  [
    { n: 1, text: 'Name your top three values. Sit with them.' },
    { n: 2, text: 'Ask: which of these did I honor yesterday?' },
    { n: 3, text: 'Ask: which felt most out of reach?' },
    { n: 4, text: 'Breathe. Choose one value to consciously embody today.' },
  ],
  ['My top three values are... and today I want to live the value of... by...', 'A daily habit that aligns with my values is...', 'A way my time and attention doesn\'t reflect what I value most is...'],
  'Live One Value Deliberately', 'Choose one value and take three actions today that embody it — no matter how small.',
  3,
  ['A moment today where I consciously chose my values over comfort was...', 'A value I want to honor more boldly tomorrow is...'],
  'Day 15. You\'re no longer just noticing. You\'re becoming.',
);

export const D21_DAY16 = makeDay(16,
  'Patterns of Avoidance', '"What you resist, persists. What you accept, transforms."',
  'Acceptance',
  'What You Run From',
  'Avoidance is one of the mind\'s primary strategies for managing discomfort — but it comes at a cost. What we avoid, we don\'t process. What we don\'t process, we carry. Avoidance can look like busyness, distraction, scrolling, over-planning, perfectionism, or simply "not thinking about it." The antidote isn\'t forcing confrontation — it\'s building a gentle tolerance for sitting with discomfort.',
  'Avoidance provides short-term relief but long-term amplification of anxiety and distress. Each time we avoid, we train the brain that the avoided thing is dangerous.',
  'Sitting with Discomfort',
  [
    { n: 1, text: 'Identify something you\'ve been avoiding — a conversation, a task, a feeling.' },
    { n: 2, text: 'Breathe. Bring it to mind, without acting on it.' },
    { n: 3, text: 'Notice what arises in the body.' },
    { n: 4, text: 'Stay with the sensation for 60 seconds. Then breathe out.' },
  ],
  ['Something I\'ve been avoiding is...', 'The feeling I\'m avoiding underneath it is...', 'One small step toward it that I could take is...'],
  'Face One Avoided Thing', 'Not fix it — just face it. Turn toward it for 60 seconds without distracting yourself.',
  1,
  ['Something I avoided today that I\'m now ready to look at is...', 'What I\'m learning from sitting with discomfort is...'],
  'Day 16. Courage isn\'t the absence of fear. It\'s turning toward it.',
);

export const D21_DAY17 = makeDay(17,
  'Meaningful Connection', '"The greatest thing in the world is to know how to belong to oneself."',
  'Relationships',
  'Depth Over Breadth',
  'In an age of constant connection, many people feel deeply alone. Research consistently shows that the quality — not quantity — of relationships predicts well-being. Meaningful connection requires vulnerability, which requires the self-awareness to know what you actually feel and need, and the courage to communicate it. Today\'s work is about deepening one relationship — including your relationship with yourself.',
  'Loneliness is now considered a greater health risk than obesity or smoking. But even one deeply connected relationship dramatically reduces its effects.',
  'Connection Meditation',
  [
    { n: 1, text: 'Bring someone you care about to mind. See them clearly.' },
    { n: 2, text: 'Breathe. Notice what you appreciate about them.' },
    { n: 3, text: 'Ask: what do I wish I could tell them that I haven\'t?' },
    { n: 4, text: 'Ask: what would make this relationship feel more alive?' },
  ],
  ['A relationship I want to invest more deeply in is...', 'Something I appreciate about this person that I\'ve never said is...', 'One way I could show up better in my most important relationships is...'],
  'One Act of Connection', 'Reach out to someone genuinely — not to catch up, but to tell them something true about how you feel about them.',
  1,
  ['A moment of genuine connection today was...', 'The relationship I most want to nurture going forward is...'],
  'Day 17. Depth takes time. You have the tools now.',
);

export const D21_DAY18 = makeDay(18,
  'Your Growth Edge', '"The place where you are afraid to go is where your growth is."',
  'Growth Mindset',
  'Lean Into the Uncomfortable',
  'Growth doesn\'t happen in comfort — it happens in the space just beyond it. Psychologist Carol Dweck\'s research on growth mindset shows that people who believe their capacities can develop (through effort, learning, and persistence) consistently outperform those who believe abilities are fixed. But growth mindset isn\'t just about performance — it\'s about being willing to meet yourself in unfamiliar territory.',
  'The brain\'s neuroplasticity — its ability to form new connections — remains active throughout life. You can learn, grow, and change at any age.',
  'Edge Exploration',
  [
    { n: 1, text: 'Think of an area of your life where you feel stuck or limited.' },
    { n: 2, text: 'Breathe. Ask: what am I afraid to try?' },
    { n: 3, text: 'Ask: what\'s the smallest possible step into that territory?' },
    { n: 4, text: 'Ask: what would I attempt if failure were impossible?' },
  ],
  ['An area of my life where I\'m playing it too safe is...', 'The fear holding me back from growth here is...', 'One small action I could take at my growth edge this week is...'],
  'Name Your Growth Edge', 'Identify one area where you want to grow but have been avoiding. Just naming it is the first step.',
  1,
  ['Something I attempted today that took a little courage was...', 'A belief about my own limits I\'m ready to challenge is...'],
  'Day 18. Your edges are not your limits. They\'re your invitations.',
);

export const D21_DAY19 = makeDay(19,
  'Gratitude & Perspective', '"It\'s not happiness that brings gratitude. It\'s gratitude that brings happiness."',
  'Positive Psychology',
  'The Science of Gratitude',
  'Gratitude is one of the most well-researched positive psychology interventions — and one of the most underestimated. Regular gratitude practice has been shown to increase well-being, improve sleep, reduce symptoms of depression, and strengthen relationships. But gratitude isn\'t toxic positivity — it coexists with difficulty. It\'s the practice of also noticing what\'s present and good, even when things are hard.',
  'Writing down three things you\'re grateful for, done consistently, can measurably shift baseline happiness within two weeks.',
  'Gratitude Scan',
  [
    { n: 1, text: 'Close your eyes. Breathe slowly.' },
    { n: 2, text: 'Let three things you\'re genuinely grateful for arise — not things you should be grateful for, but things that actually move you.' },
    { n: 3, text: 'For each one, breathe in and feel the appreciation.' },
    { n: 4, text: 'Open your eyes. Let the feeling linger.' },
  ],
  ['Three things I\'m genuinely grateful for today are...', 'Something ordinary I\'ve been taking for granted is...', 'A person I\'m grateful for who I\'ve never fully told is...'],
  'Find Beauty in One Ordinary Thing', 'Pick something small and mundane today — a cup of tea, a quiet moment, the feeling of clean sheets. Let yourself fully appreciate it.',
  1,
  ['A moment today that I want to hold onto is...', 'Something I\'m grateful for about this 21-day practice is...'],
  'Day 19. Gratitude isn\'t about ignoring hard things. It\'s about also noticing the good.',
);

export const D21_DAY20 = makeDay(20,
  'Sustainable Practice', '"Long-term consistency beats short-term intensity."',
  'Habit Design',
  'Making Awareness a Way of Life',
  'The most important question at the end of any intensive practice isn\'t "what did I learn?" — it\'s "how do I keep this alive?" Behavioral science shows that sustainable habits require three things: a clear cue, a simple routine, and a meaningful reward. The goal is not to add another obligation to your life — it\'s to weave small moments of reflection so naturally into your day that they become invisible.',
  'The smallest habit, done consistently, creates more lasting change than any dramatic but inconsistent effort.',
  'Habit Architecture',
  [
    { n: 1, text: 'Think of one reflective practice from this journal that felt most useful.' },
    { n: 2, text: 'Ask: when in my day could this happen naturally — attached to an existing routine?' },
    { n: 3, text: 'Make it tiny: what\'s the smallest possible version of this practice?' },
    { n: 4, text: 'Breathe. Commit to this one small thing.' },
  ],
  ['The practice from these 21 days I most want to continue is...', 'A natural trigger in my day where I could attach it is...', 'The smallest, most sustainable version of this habit looks like...'],
  'Design Your Daily Practice', 'Write down one tiny reflective practice you\'ll do every day going forward — small enough that you can\'t say no on a hard day.',
  1,
  ['One thing I\'ve changed about myself or my life during this practice is...', 'What I\'m committed to continuing after day 21 is...'],
  'Day 20. One day left. You\'ve already begun something that will last.',
);

export const D21_DAY21 = makeDay(21,
  'You Have Arrived', '"You are already what you are seeking."',
  'Integration — Day 21',
  'The Practice Was the Point',
  'Twenty-one days. You showed up, day after day, and turned toward yourself. Not to fix what\'s broken, but to see more clearly. Self-awareness isn\'t a final state you achieve — it\'s the practice of returning, again and again, to the present moment with honesty and compassion. Today, we don\'t introduce anything new. We simply honor the journey and the person who took it.',
  'After 21 days of consistent practice, the brain has begun to form new habitual pathways. What felt effortful at the beginning is becoming natural.',
  'The Return',
  [
    { n: 1, text: 'Close your eyes. Breathe slowly and deeply.' },
    { n: 2, text: 'Let your attention rest inside yourself — not on thoughts, not on plans.' },
    { n: 3, text: 'Just be here. Exactly as you are. Exactly as you\'ve always been.' },
    { n: 4, text: 'Notice: this is the place you\'ve been finding your way back to all along.' },
  ],
  ['Over 21 days, the most important thing I\'ve learned about myself is...', 'A gift I\'m giving to my future self from this practice is...', 'What I would tell someone just starting this journey is...'],
  'Write Your Own Closing Reflection', 'No prompts. No structure. Just you and the page. Write whatever feels true right now.',
  1,
  ['The version of myself I feel I\'m growing into is...', 'I close this journal feeling...'],
  'You did it. Twenty-one days. The inward journey continues — and now you know the way.',
);

// Export all 21 days as an ordered array
export const TWENTY_ONE_DAY_CONTENTS = [
  D21_DAY1, D21_DAY2, D21_DAY3, D21_DAY4, D21_DAY5, D21_DAY6, D21_DAY7,
  D21_DAY8, D21_DAY9, D21_DAY10, D21_DAY11, D21_DAY12, D21_DAY13, D21_DAY14,
  D21_DAY15, D21_DAY16, D21_DAY17, D21_DAY18, D21_DAY19, D21_DAY20, D21_DAY21,
];
