// Expo Config Plugin: withRustCore
//
// Re-applies the native Rust bridge wiring that manual edits to ios/ and
// android/ would otherwise lose whenever `npx expo prebuild` regenerates the
// native projects. Everything here is idempotent — safe to run on every
// prebuild without duplicating edits.
//
// iOS:
//   - refuses project paths with a space (CocoaPods URI crash on :podspec)
//   - if InwardCore.xcframework exists, links local InwardCore + uniffi via :path
//   - if it does not, skips those pods so `expo run:ios` still launches (JS mock)
// Android:
//   - points the Gradle `jniLibs` sourceSet at src/main/jniLibs, where
//     scripts/build-android.sh drops the cross-compiled libinward_core.so.
//   - keeps legacy .so packaging so debug and release both load libswa-mobile.
const {
  withPodfile,
  withAppBuildGradle,
  withAndroidManifest,
  withDangerousMod,
  createRunOncePlugin,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// NEVER use CocoaPods `:podspec => '/abs/path/file.podspec'`.
// CocoaPods treats that as a URI; a space in the folder name (e.g. "swa 2")
// crashes with: bad URI (is not URI?): ".../uniffi-bindgen-react-native.podspec"
// Always use `:path =>` + File.expand_path, and refuse paths with spaces.
const SPACE_GUARD_BLOCK = `# >>> withRustCore:guard
if __dir__.include?(' ')
  raise <<~SWA
    [SWA] CocoaPods cannot install this project from a folder whose path contains a space.

    Current iOS folder:
      #{__dir__}

    That is what caused:
      bad URI (is not URI?): ".../uniffi-bindgen-react-native.podspec"

    Fix once, then start the app:

      mv "$HOME/Downloads/swa 2" "$HOME/swa"
      cd ~/swa
      npm install
      rm -rf apps/mobile/ios
      cd apps/mobile && npx expo run:ios

    See START.md in the repo root.
  SWA
end
# <<< withRustCore:guard
`;

const RUST_PODS_BLOCK = `  # >>> withRustCore:pods
  uniffi_dir = [
    File.expand_path('../../../node_modules/uniffi-bindgen-react-native', __dir__),
    File.expand_path('../node_modules/uniffi-bindgen-react-native', __dir__),
  ].find { |candidate| File.directory?(candidate) }
  unless uniffi_dir
    raise "[SWA] uniffi-bindgen-react-native is not installed. From the repo root run: npm install"
  end
  pod 'uniffi-bindgen-react-native', :path => uniffi_dir
  pod 'InwardCore', :path => File.expand_path('..', __dir__)
  # <<< withRustCore:pods
`;

const ANDROID_MARKER = '// withRustCore: jniLibs sourceSet';
const ANDROID_PACKAGING_MARKER = '// withRustCore: native packaging';

// The bridge sources generated by ubrn that prebuild would otherwise delete.
const IOS_BRIDGE_HEADER = `// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "inward-core.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import <ReactCodegen/InwardCore/InwardCore.h>

@interface InwardCore : NSObject <NativeInwardCoreSpec>
#else
#import <React/RCTBridgeModule.h>

@interface InwardCore : NSObject <RCTBridgeModule>
#endif

@end
`;

const IOS_BRIDGE_MM = `// Generated by uniffi-bindgen-react-native
#import "InwardCore.h"

namespace uniffi_generated {
    using namespace facebook::react;
    /**
    * ObjC++ class for module 'NativeInwardCore'
    */
    class JSI_EXPORT NativeInwardCoreSpecJSI : public ObjCTurboModule {
    public:
        NativeInwardCoreSpecJSI(const ObjCTurboModule::InitParams &params);
        std::shared_ptr<CallInvoker> callInvoker;
    };

    static facebook::jsi::Value __hostFunction_InwardCore_installRustCrate(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
        auto& tm = static_cast<NativeInwardCoreSpecJSI&>(turboModule);
        auto jsInvoker = tm.callInvoker;
        uint8_t result = inwardcore::installRustCrate(rt, jsInvoker);
        return facebook::jsi::Value(rt, result);
    }
    static facebook::jsi::Value __hostFunction_InwardCore_cleanupRustCrate(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
        uint8_t result = inwardcore::cleanupRustCrate(rt);
        return facebook::jsi::Value(rt, result);
    }

    NativeInwardCoreSpecJSI::NativeInwardCoreSpecJSI(const ObjCTurboModule::InitParams &params)
        : ObjCTurboModule(params), callInvoker(params.jsInvoker) {
            this->methodMap_["installRustCrate"] = MethodMetadata {1, __hostFunction_InwardCore_installRustCrate};
            this->methodMap_["cleanupRustCrate"] = MethodMetadata {1, __hostFunction_InwardCore_cleanupRustCrate};
    }
} // namespace uniffi_generated

@implementation InwardCore
RCT_EXPORT_MODULE()

// Don't compile this code when we build for the old architecture.
#ifdef RCT_NEW_ARCH_ENABLED

- (NSNumber *)installRustCrate {
    @throw [NSException exceptionWithName:@"UnreachableException"
                        reason:@"This method should never be called."
                        userInfo:nil];
}

- (NSNumber *)cleanupRustCrate {
    @throw [NSException exceptionWithName:@"UnreachableException"
                        reason:@"This method should never be called."
                        userInfo:nil];
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
    return std::make_shared<uniffi_generated::NativeInwardCoreSpecJSI>(params);
}
#endif

@end
`;

function stripWithRustCoreBlocks(podfile) {
  return podfile
    .replace(/# >>> withRustCore:guard[\s\S]*?# <<< withRustCore:guard\n?/g, '')
    .replace(/# >>> withRustCore:pods[\s\S]*?# <<< withRustCore:pods\n?/g, '')
    .replace(/^[ \t]*pod ['"]InwardCore['"][^\n]*\n?/gm, '')
    .replace(/^[ \t]*pod ['"]uniffi-bindgen-react-native['"][^\n]*\n?/gm, '');
}

function hasInwardCoreXcframework(projectRoot) {
  return fs.existsSync(path.join(projectRoot, 'build', 'InwardCore.xcframework'));
}

const withRustCoreIOS = (config) =>
  withPodfile(config, (modConfig) => {
    let podfile = stripWithRustCoreBlocks(modConfig.modResults.contents);

    if (!podfile.includes('# >>> withRustCore:guard')) {
      podfile = `${SPACE_GUARD_BLOCK}\n${podfile}`;
    }

    const projectRoot = modConfig.modRequest.projectRoot;
    const rustReady = hasInwardCoreXcframework(projectRoot);
    if (rustReady) {
      if (!podfile.includes('# >>> withRustCore:pods')) {
        const next = podfile.replace(
          /use_native_modules!\s*\([^\n]*$/m,
          (match) => `${match}\n${RUST_PODS_BLOCK}`,
        );
        if (next === podfile) {
          console.warn(
            '[withRustCore] Could not find use_native_modules! in the Podfile; Rust pods were not added.',
          );
        }
        podfile = next;
      }
      console.log('[withRustCore] Linking InwardCore + uniffi-bindgen-react-native (XCFramework present).');
    } else {
      console.warn(
        '[withRustCore] InwardCore.xcframework not found. iOS will build without the Rust pod and use the JS mock engine. To enable the real backend: ./scripts/build-ios.sh && rm -rf apps/mobile/ios && cd apps/mobile && npx expo run:ios',
      );
    }

    modConfig.modResults.contents = podfile;
    return modConfig;
  });

// Recreate the ubrn bridge sources that prebuild wipes from ios/.
const withRustCoreIOSBridge = (config) =>
  withDangerousMod(config, [
    'ios',
    async (config) => {
      const iosDir = path.join(config.modRequest.projectRoot, 'ios');
      if (!fs.existsSync(iosDir)) return config;
      const files = {
        'InwardCore.h': IOS_BRIDGE_HEADER,
        'InwardCore.mm': IOS_BRIDGE_MM,
      };
      for (const [name, contents] of Object.entries(files)) {
        const target = path.join(iosDir, name);
        if (!fs.existsSync(target)) {
          fs.writeFileSync(target, contents, 'utf8');
        }
      }
      return config;
    },
  ]);

const withRustCoreAndroid = (config) =>
  withAppBuildGradle(config, (config) => {
    let contents = config.modResults.contents;
    if (!contents.includes(ANDROID_MARKER)) {
      contents += `

${ANDROID_MARKER}
android {
  sourceSets {
    main {
      jniLibs.srcDirs = ['src/main/jniLibs']
    }
  }
}
`;
    }
    if (!contents.includes(ANDROID_PACKAGING_MARKER)) {
      contents += `

${ANDROID_PACKAGING_MARKER}
android {
  packagingOptions {
    jniLibs {
      useLegacyPackaging true
    }
    pickFirst '**/libc++_shared.so'
    pickFirst '**/libfbjni.so'
  }
}
`;
    }
    config.modResults.contents = contents;
    return config;
  });

// Export writes JSON to the public Download/swa folder. On Android <= 10 that
// uses the legacy storage path (WRITE_EXTERNAL_STORAGE + requestLegacyExternal
// Storage); on 11+ the app falls back to the Storage Access Framework instead.
const withRustCoreAndroidManifest = (config) =>
  withAndroidManifest(config, (config) => {
    const manifest = config.modResults.manifest;
    const perms = manifest['uses-permission'] || (manifest['uses-permission'] = []);
    const write = perms.find(
      (p) => p.$['android:name'] === 'android.permission.WRITE_EXTERNAL_STORAGE',
    );
    if (write) {
      write.$['android:maxSdkVersion'] = '29';
    } else {
      perms.push({
        $: {
          'android:name': 'android.permission.WRITE_EXTERNAL_STORAGE',
          'android:maxSdkVersion': '29',
        },
      });
    }
    const app = manifest.application?.[0];
    if (app) {
      app.$['android:requestLegacyExternalStorage'] = 'true';
    }
    return config;
  });

const withRustCore = (config) => {
  config = withRustCoreIOS(config);
  config = withRustCoreIOSBridge(config);
  config = withRustCoreAndroid(config);
  config = withRustCoreAndroidManifest(config);
  return config;
};

module.exports = createRunOncePlugin(withRustCore, 'withRustCore', '1.2.0');
