// Expo Config Plugin: withRustCore
//
// Re-applies the native Rust bridge wiring that manual edits to ios/ and
// android/ would otherwise lose whenever `npx expo prebuild` regenerates the
// native projects. Everything here is idempotent — safe to run on every
// prebuild without duplicating edits.
//
// iOS:
//   - re-declares the local `InwardCore` pod (apps/mobile/InwardCore.podspec),
//     which vendors the Rust XCFramework + C++ JSI glue, and
//   - re-declares the local `uniffi-bindgen-react-native` podspec dependency.
// Android:
//   - points the Gradle `jniLibs` sourceSet at src/main/jniLibs, where
//     scripts/build-android.sh drops the cross-compiled libinward_core.so.
const {
  withPodfile,
  withAppBuildGradle,
  withDangerousMod,
  createRunOncePlugin,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const POD_INWARD_CORE = "  pod 'InwardCore', :path => '../'";
const POD_UNIFFI =
  "  pod 'uniffi-bindgen-react-native', :podspec => '../../../node_modules/uniffi-bindgen-react-native/uniffi-bindgen-react-native.podspec'";

const ANDROID_MARKER = '// withRustCore: jniLibs sourceSet';

// The bridge sources generated by ubrn that prebuild would otherwise delete.
const IOS_BRIDGE_HEADER = `// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "inward-core.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import <ReactCodegen/InwardCore/InwardCore.h>

@interface InwardCore : NSObject <NativeInwardCoreSpec>
#else
#import <React/RCTBridgeModule.h>

@interface InwardCore : NSObject <RCTBridgeModule>
#endif

@end
`;

const IOS_BRIDGE_MM = `// Generated by uniffi-bindgen-react-native
#import "InwardCore.h"

namespace uniffi_generated {
    using namespace facebook::react;
    /**
    * ObjC++ class for module 'NativeInwardCore'
    */
    class JSI_EXPORT NativeInwardCoreSpecJSI : public ObjCTurboModule {
    public:
        NativeInwardCoreSpecJSI(const ObjCTurboModule::InitParams &params);
        std::shared_ptr<CallInvoker> callInvoker;
    };

    static facebook::jsi::Value __hostFunction_InwardCore_installRustCrate(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
        auto& tm = static_cast<NativeInwardCoreSpecJSI&>(turboModule);
        auto jsInvoker = tm.callInvoker;
        uint8_t result = inwardcore::installRustCrate(rt, jsInvoker);
        return facebook::jsi::Value(rt, result);
    }
    static facebook::jsi::Value __hostFunction_InwardCore_cleanupRustCrate(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
        uint8_t result = inwardcore::cleanupRustCrate(rt);
        return facebook::jsi::Value(rt, result);
    }

    NativeInwardCoreSpecJSI::NativeInwardCoreSpecJSI(const ObjCTurboModule::InitParams &params)
        : ObjCTurboModule(params), callInvoker(params.jsInvoker) {
            this->methodMap_["installRustCrate"] = MethodMetadata {1, __hostFunction_InwardCore_installRustCrate};
            this->methodMap_["cleanupRustCrate"] = MethodMetadata {1, __hostFunction_InwardCore_cleanupRustCrate};
    }
} // namespace uniffi_generated

@implementation InwardCore
RCT_EXPORT_MODULE()

// Don't compile this code when we build for the old architecture.
#ifdef RCT_NEW_ARCH_ENABLED

- (NSNumber *)installRustCrate {
    @throw [NSException exceptionWithName:@"UnreachableException"
                        reason:@"This method should never be called."
                        userInfo:nil];
}

- (NSNumber *)cleanupRustCrate {
    @throw [NSException exceptionWithName:@"UnreachableException"
                        reason:@"This method should never be called."
                        userInfo:nil];
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
    return std::make_shared<uniffi_generated::NativeInwardCoreSpecJSI>(params);
}
#endif

@end
`;

const withRustCoreIOS = (config) =>
  withPodfile(config, (config) => {
    const podfile = config.modResults.contents;
    if (!podfile.includes("pod 'InwardCore'")) {
      // Insert right after the auto-generated autolinking call.
      config.modResults.contents = podfile.replace(
        /use_native_modules!\s*\([^\n]*$/m,
        (match) => `${match}\n${POD_INWARD_CORE}\n${POD_UNIFFI}`,
      );
    }
    return config;
  });

// Recreate the ubrn bridge sources that prebuild wipes from ios/.
const withRustCoreIOSBridge = (config) =>
  withDangerousMod(config, [
    'ios',
    async (config) => {
      const iosDir = path.join(config.modRequest.projectRoot, 'ios');
      if (!fs.existsSync(iosDir)) return config;
      const files = {
        'InwardCore.h': IOS_BRIDGE_HEADER,
        'InwardCore.mm': IOS_BRIDGE_MM,
      };
      for (const [name, contents] of Object.entries(files)) {
        const target = path.join(iosDir, name);
        if (!fs.existsSync(target)) {
          fs.writeFileSync(target, contents, 'utf8');
        }
      }
      return config;
    },
  ]);

const withRustCoreAndroid = (config) =>
  withAppBuildGradle(config, (config) => {
    const contents = config.modResults.contents;
    if (!contents.includes(ANDROID_MARKER)) {
      config.modResults.contents = `${contents}\n\n${ANDROID_MARKER}\nandroid {\n  sourceSets {\n    main {\n      jniLibs.srcDirs = ['src/main/jniLibs']\n    }\n  }\n}\n`;
    }
    return config;
  });

const withRustCore = (config) => {
  config = withRustCoreIOS(config);
  config = withRustCoreIOSBridge(config);
  config = withRustCoreAndroid(config);
  return config;
};

module.exports = createRunOncePlugin(withRustCore, 'withRustCore', '1.0.0');
